// <auto-generated />
namespace Projektarbete_MVC1_JonasAlden.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tabortIsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabortIsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201710020828042_tabortIsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
